#Bugs
1. I had this error "TypeError: __init__() got an unexpected keyword argument 'providing_args'" while trying to migrate the allauth app.
I uninstalled django and reinstalled it, thereafter running python3 manage.py migrate which worked successfully.

2. I had this error "cp: cannot stat '../.pip-modules/lib/python3.7/site-packages/allauth/templates/*': No such file or directory" while trying to copy the templates recursively.
Tutor support guided me in finding the django-allauth directory.

Images
Homepage banner image by Silvia from pixabay
Image by Freepik

blog
https://www.kitchen-concoctions.com/2012/05/avocado-banana-hair-mask/